// Baseline data for RVNL Reporting Tool (June 2026 Only)
const INITIAL_DATA = [
  {
    "type": "Creative / Collateral",
    "subType": "Video",
    "title": "Vande Bharat Video",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 3",
    "date": "",
    "owner": "Sanjam",
    "remarks": "Sent to client: on 21st Nov - 2:57 PM. On hold client to update.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "9e6fbb0d-4542-4ce3-bd0e-7f4d5f0e19ec",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Video",
    "title": "Solar - Video + Caption",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 3",
    "date": "",
    "owner": "Suvrata",
    "remarks": "On hold client to update.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "17adb34b-2e5b-4e23-b144-a74b7e6e58ee",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Video",
    "title": "Bardhaman Video - Script + Caption",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 3",
    "date": "",
    "owner": "Alka",
    "remarks": "Sent to client: final changes sent on 15th jan. On hold client to update.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "0e75ea0d-1da9-4853-8a45-9f00a2930305",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Video",
    "title": "The Indore-Budni New Broad Gauge Rail Line Project",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 3",
    "date": "",
    "owner": "Komal",
    "remarks": "Revised video sent to client on 21st march. On hold client to update.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "1d40c22d-be6d-465b-a778-bb37e6708e44",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Banner",
    "title": "VARTA 24 Banner (2 static options)",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 1",
    "date": "",
    "owner": "Eesha",
    "remarks": "Sent to client for approval.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "5d8d340a-df67-41ae-ad6d-624780f7bda3",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Video",
    "title": "TV ad spot 60 second cut of corporate film",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 1",
    "date": "",
    "owner": "Durgesh",
    "remarks": "Sent to client.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "4ecdb912-8839-4173-92e4-88c7e60a536a",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Design",
    "title": "RVNL hiring GM Civil",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 1",
    "date": "",
    "owner": "Puja",
    "remarks": "Sent to client.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "d2b3fbe1-238f-44de-b653-5b9063b92aba",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "Yoga Day",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 3",
    "date": "",
    "owner": "Sanjam",
    "remarks": "Sent to client.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "3d515d49-2666-484b-ae84-78490eb6d188",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "Blood Donor Day",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 2",
    "date": "",
    "owner": "Suvrata",
    "remarks": "Sent to client.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "4e0f8cb6-7418-4424-8ccf-817ecb6fba61",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "Fathers Day Creative",
    "status": "Awaiting Approval",
    "month": "June 2026",
    "week": "Week 2",
    "date": "",
    "owner": "Alka",
    "remarks": "Sent to client.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "e0b429d1-6163-45b3-913a-e7ab661ce06e",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Creative / Collateral",
    "subType": "Blog",
    "title": "RVNL Article",
    "status": "In Progress",
    "month": "June 2026",
    "week": "Week 2",
    "date": "",
    "owner": "Komal",
    "remarks": "WIP.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "5510d4db-076d-4d51-aa6e-aec00a942582",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "Vande bharat repost caption kinet solutions",
    "status": "Not Published",
    "month": "June 2026",
    "week": "Week 2",
    "date": "",
    "owner": "Eesha",
    "remarks": "Sent to client not used.",
    "canvaLink": "",
    "liveLink": "",
    "image": "",
    "id": "74e9f1f8-047e-416a-a471-860e8d3413cf",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL kolkata metro new garia update",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "2nd June",
    "owner": "Durgesh",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl_rvnl-kolkatametro-infrastructure-activity-7467653199236079616-qE0J",
    "image": "",
    "id": "1f335388-eedf-4543-b289-681d4a250e13",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL janam tv 60 second video",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "2nd June",
    "owner": "Puja",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl_rvnl-janam-tv-ad-activity",
    "image": "",
    "id": "9d41d09c-7346-4c7e-bb64-9615f294e695",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL environment day carousel",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "5th June",
    "owner": "Sanjam",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-environment-day",
    "image": "",
    "id": "3dc8e519-3774-489c-9560-34adb92f13a9",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL hiring general manager Civil",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "6th June",
    "owner": "Suvrata",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-hiring-gm-civil",
    "image": "",
    "id": "1de6f28b-1669-4349-b76b-adb41855227c",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL dental camp carousel",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "6th June",
    "owner": "Alka",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-dental-camp",
    "image": "",
    "id": "cc9e8491-3581-43c1-9078-90cc6f1c2fbc",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "RVNL hiring project manager",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 1",
    "date": "6th June",
    "owner": "Komal",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-hiring-pm",
    "image": "",
    "id": "27650251-ef0a-4016-8383-6f131fe81c48",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "World Oceans Day",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 2",
    "date": "8th June",
    "owner": "Eesha",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-world-oceans-day",
    "image": "",
    "id": "e3e232de-0b05-4818-90de-a875663f73ca",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "CSR new school building",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 2",
    "date": "8th June",
    "owner": "Durgesh",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-csr-school",
    "image": "",
    "id": "597082dc-a1d3-4921-ad09-8953dca99ab1",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "CMD announcement post twitter",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 2",
    "date": "9th June",
    "owner": "Puja",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-cmd-announcement",
    "image": "",
    "id": "2b09935e-7381-494d-8e8f-3376e1fc524f",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  },
  {
    "type": "Social Media",
    "subType": "Social Media",
    "title": "LOA south central railway",
    "status": "Published",
    "month": "June 2026",
    "week": "Week 2",
    "date": "9th June",
    "owner": "Sanjam",
    "remarks": "",
    "canvaLink": "",
    "liveLink": "https://www.linkedin.com/posts/rvnl-loa-scr",
    "image": "",
    "id": "8ceba96e-5149-48ea-8409-24175dcb2b27",
    "spokesperson": "",
    "publication": "",
    "impressions": "",
    "engagement": ""
  }
];
